name: Diabetes Workflow CI

on:
  push:
    branches: [main]

jobs:
  train-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          # Menambahkan setuptools dan wheel agar build-docker lancar
          pip install mlflow scikit-learn pandas setuptools wheel

      - name: Run mlflow project
        run: |
          mlflow run MLProject/ --env-manager local

      - name: Get latest MLflow run_id
        id: run_id
        run: |
          # Mengambil folder ID terbaru di dalam mlruns/0
          RUN_ID=$(ls mlruns/0 | grep -v 'meta.yaml' | sort | tail -n 1)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: diabetes-model
          path: mlruns/0/${{ steps.run_id.outputs.RUN_ID }}/artifacts/model

      - name: Build Docker Model
        run: |
          mlflow models build-docker -m mlruns/0/${{ steps.run_id.outputs.RUN_ID }}/artifacts/model -n diabetes-predictor

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and Push Docker Image
        run: |
          # Menggunakan username dari secrets agar tidak hardcoded
          docker tag diabetes-predictor ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-predictor:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-predictor:latest
