name: Diabetes Workflow CI

on:
  push:
    branches: [main]

jobs:
  train-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn pandas setuptools wheel

      - name: Run mlflow project
        run: |
          # Menjalankan training (mlruns akan tercipta di root)
          mlflow run MLProject/ --env-manager local

      - name: Get latest MLflow run_id
        id: run_id
        run: |
          # Gunakan Python untuk mengambil ID terakhir dari folder mlruns manapun 
          RUN_ID=$(python -c "import mlflow; print(mlflow.search_runs().iloc[0]['run_id'])")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_OUTPUT
          echo "Berhasil mendapatkan ID: $RUN_ID"

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: diabetes-model
          # Jalur dikembalikan ke root mlruns
          path: mlruns/0/${{ steps.run_id.outputs.RUN_ID }}/artifacts/model

      - name: Build Docker Model
        run: |
          # Jalur dikembalikan ke root mlruns
          mlflow models build-docker -m mlruns/0/${{ steps.run_id.outputs.RUN_ID }}/artifacts/model -n diabetes-predictor

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and Push Docker Image
        run: |
          docker tag diabetes-predictor ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-predictor:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-predictor:latest