name: Diabetes Workflow CI

on:
  push:
    branches: [main]

jobs:
  train-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn pandas setuptools wheel

      - name: Run mlflow project
        run: |
          mlflow run MLProject/ --env-manager local

      - name: Get latest MLflow run_id
        id: run_id
        run: |
          # Mencari folder 'model' secara otomatis
          FINAL_PATH=$(find . -name "MLmodel" -exec dirname {} \;)
          echo "MODEL_PATH=$FINAL_PATH" >> $GITHUB_OUTPUT
          echo "Model ditemukan di: $FINAL_PATH"

      - name: Install Python dependencies
        run: |
          echo "All dependencies verified."

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: diabetes-model
          path: ${{ steps.run_id.outputs.MODEL_PATH }}

      - name: Build Docker Model
        run: |
          mlflow models build-docker -m ${{ steps.find_path.outputs.MODEL_PATH }} -n diabetes-predictor

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag diabetes-predictor ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-predictor:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-predictor:latest
