name: Diabetes Workflow CI

on:
  push:
    branches: [main]

jobs:
  train-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn pandas setuptools wheel

      - name: Run mlflow project
        run: |
          mlflow run MLProject/ --env-manager local

      - name: Get latest MLflow run_id
        id: get_id
        run: |
          # Mencari folder yang berisi file 'MLmodel' di seluruh direktori
          # Lalu mengambil jalur (path) folder tersebut
          MODEL_PATH=$(find . -name "MLmodel" -exec dirname {} \; | head -n 1)
          echo "FINAL_PATH=$MODEL_PATH" >> $GITHUB_OUTPUT
          echo "Path Model ditemukan: $MODEL_PATH"

      - name: Install Python dependencies
        run: |
          echo "All deployment dependencies verified."

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: diabetes-model
          path: ${{ steps.get_id.outputs.FINAL_PATH }}

      - name: Build Docker Model
        run: |
          # Menggunakan variabel FINAL_PATH yang sudah didapatkan sebelumnya
          mlflow models build-docker -m ${{ steps.get_id.outputs.FINAL_PATH }} -n diabetes-predictor

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag diabetes-predictor ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-predictor:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-predictor:latest
